feat: add custom node filter data
flow-build/workflow-api pull request #117
Opened 2022-12-06 12:32 UTC by junrongzhu1

Implement customNode filter data.

2022-12-06 13:06 UTC, gustavo-fdte commented
(!) Bunnyshell could not create the Environment *App-main-branch / feat/customNode-filterData:master / PR-117* for PR #117.

2022-12-06 14:21 UTC, pedropereiraassis requested changes

2022-12-06 14:21 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +                  ]
Precisa aceitar o tipo 'object' também para casos de $ref, $js, etc.. (O mesmo vale para o 'keys')

2022-12-06 14:21 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +      const { key, data, values } = executionData;
É bom validar aqui também os tipos de 'key', 'data' e 'values' para casos em que sejam passados tipos diferentes do esperado na execução do nó.

2022-12-06 14:21 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +        if (_.get(item, key) === values[0]) {
Dessa maneira você sempre está fazendo a comparação com 'values[0]'.. precisa usar uma iteração nele para passar por todos os valores do array 'values' e não só o primeiro como está.
Precisa também verificar antes se o values é array ou string para essa lógica (pois pelo que entendi no código essa variável pode ser string ou array). - OBS: validar se realmente pode ser string ou array, ou se sempre será array.

2022-12-06 15:09 UTC, gustavo-fdte requested changes

2022-12-10 14:21 UTC, pedropereiraassis requested changes

2022-12-10 14:21 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +                    {
Pelo que entendi, agora o primary_keys deveria ser somente do tipo 'object', não?

2022-12-10 14:21 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +  static validate(spec) {
Como você está usando o método `validateExecutionData` conforme usado no remapData, precisa aceitar o parâmetro `schema = null` no método `validate`, e alterar a linha 64 para receber o schema que vem na função ou usar o do `get schema`

2022-12-10 14:21 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +    try {
É necessário validar se o `data` e `primary_keys` são do tipo correto. Você criou o método `validateExecutionData` mas ele não é chamado.

2022-12-10 14:21 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +      const keys = Object.keys(primary_keys);
Pelo schema do `get schema` e do `validateExecutionData` aparentemente o primary_keys pode ser array ou objeto. Se for array o código quebra nessa linha 88. Validar se realmente pode ser array ou se será somente objeto.

2022-12-10 15:16 UTC, pedropereiraassis commented on src/nodes/filterDataNode.js
> +        primary_keys: { type: "object", items: { type: "string" } }
Esse schema para o `primary_keys` está correto?

2022-12-10 15:49 UTC, pedropereiraassis approved these changes

2022-12-13 15:02 UTC, gustavo-fdte approved these changes

2022-12-13 15:07 UTC, merged