Feature/flow 98
flow-build/workflow-api pull request #222
Opened 2023-05-16 13:54 UTC by imagure

**What type of PR is this?**
feature

**What this PR does / why we need it**:
it adds new route on /connection/beacon to emit message trough desired broker

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., usage docs, etc.**:

```docs
it takes an optional query string containing the broker reference
broker=MQTT|KAFKA|AMQP
Default value (if not sent) is "MQTT")

curl --location 'localhost:3000/connection/beacon?broker=MQTT' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rvcl9pZCI6IjYyYjU0NWQwLWYzZTktMTFlZC05ZDZhLTBkZDc5NDY2NjljYSIsImNsYWltcyI6W10sInNlc3Npb25faWQiOiJocE92RloxTDZWb0l4cVJJS0lDLUYiLCJpYXQiOjE2ODQyNDE5MjIsImV4cCI6MTY5MDI0MTkyMn0.VDnLCGcLQOgYKhxC9hTCw-8kv00aPbITgXs6SiP17NM' \
--header 'Content-Type: application/json' \
--data '{
  "userId": "e45e5021-16a4-4450-8018-35f0aadc0b31"
}'
```

2023-05-16 14:11 UTC, pedropereiraassis approved these changes

2023-05-16 14:35 UTC, gustavo-fdte requested changes

2023-05-16 14:35 UTC, gustavo-fdte commented on src/controllers/connection.js
> +      flowbuild_host: process.env.FLOWBUILD_URL
Não é estranho definir sua própria URL na aplicação?

2023-05-16 14:35 UTC, gustavo-fdte commented on src/controllers/connection.js
> +  const brokerQS = ctx.request?.query?.broker;
Porque permitir que a QS defina MQTT e não os demais?
Ao meu ver, a requisição é para postar a mensagem no(s) broker(s) que o server estiver operando e não escolher o broker para enviar.

2023-05-16 14:35 UTC, gustavo-fdte commented on src/routers/mainRouter.js
> +  const connection = new Router();
eu havia pensado em deixar esse router no cockpit e não no main.
Na minha cabeça, o main router é o router de execução e o cockpit são rotas acessórias.

2023-05-17 12:39 UTC, gustavo-fdte requested changes

2023-05-17 12:39 UTC, gustavo-fdte commented on src/controllers/connection.js
> +    switch (broker) {
2 considerações
1. pessoalmente não gosto de switch, prefiro fazer um object assign para direcionar para as soluções.
2. acho ruim essa função publishMessage ter assinaturas distintas para diferentes tipos de broker, parece faltar uma abstração que deveria ser feita na função (p.ex.: estrutura do tópico, mapeamento do objeto de entrada)

2023-05-18 12:20 UTC, gustavo-fdte approved these changes

2023-05-18 12:22 UTC, merged